fixup! [op][n_upsable][media] Support for enabling use_neva_v4l2_codec
:Release Notes:
Fix compilation error when enable use_neva_v4l2_codec

:Detailed Notes:
Fixes:
| ERROR at //media/gpu/BUILD.gn:539:5: Assertion failed.
|     assert(enable_av1_decoder)
|     ^-----
| See //media/BUILD.gn:163:5: which caused the file to be included.
|     "//media/gpu:unit_tests",
|     ^-----------------------

This patch set fixes above assertion which arise because we enable
use__v4l2_codec but enable_av1_decoder is disable for webos

:Testing Performed:
Build is successful.

:QA Notes:
Test-cases: build-only

:Issues Addressed:
N/A

Change-Id: I681be07af62db31c850b21136bafa28d4dec75d6
Reviewed-on: http://gpro.lge.com/c/webosose/chromium91/+/328462
Tested-by: Pankaj Maharana <pankaj.maharana@lge.com>
Reviewed-by: Pankaj Maharana <pankaj.maharana@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>